[package]
name = "music_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
rand = "0.8.5"
ratatui = "0.29.0"
rodio = "0.19.0"
serde = {version="1.0.214", features=["derive"]}
serde_json = "1.0.132"
