[package]
name = "music_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
rodio = "0.19.0"
serde = {version="1.0.214", features=["derive"]}
serde_json = "1.0.132"
